name: Build and Deploy RemoteBESA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        settings-path: ${{ github.workspace }}
    
    - name: Configure Maven settings
      run: |
        mkdir -p ~/.m2
        cp .github/maven-settings.xml ~/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build with Maven (GitHub Packages profile)
      run: mvn clean compile package -P github-packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Deploy to GitHub Packages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: mvn deploy -P github-packages -DskipTests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
